AWSTemplateFormatVersion: "2010-09-09"
Description: Creates the Building section of the API
Parameters:
  BucketName:
    Type: String
    Default: energicostestbucket
  DomainName:
    Type: String
    Default: api.example.com
Resources:
  Building:
    Type: AWS::ApiGateway::RestApi
    Properties:
      BodyS3Location:
        Bucket: !Ref BucketName
        Key: building-swagger.yaml
      FailOnWarnings: false
  BuildingMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: "buildings"
      DomainName: !Ref DomainName
      RestApiId: !Ref Building
