AWSTemplateFormatVersion: "2010-09-09"
Description: |
  This Stack describes the DynamoDB Tables used for Energicos project
Resources:
  Energecos:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:  EnergecosTable
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: pk_id
          AttributeType: S
        - AttributeName: tg_id
          AttributeType: S
      KeySchema:
        - AttributeName: pk_id
          KeyType: HASH
        - AttributeName: tg_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: tg_id
              KeyType: HASH
            - AttributeName: pk_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
Outputs:
  Table:
    Description: The DynamoDB Table for the Energecos Project
    Value: !Ref Energecos
    Export:
      Name: EnergecosTable